package nz.co.activiti.tutorial.rest.ds.group;

import java.util.Map;

import nz.co.activiti.tutorial.rest.model.GenericCollectionModel;
import nz.co.activiti.tutorial.rest.model.PagingAndSortingParameter;
import nz.co.activiti.tutorial.rest.model.group.Group;
import nz.co.activiti.tutorial.rest.model.group.GroupQueryParameter;
import nz.co.activiti.tutorial.rest.model.group.MemberShip;

public interface GroupRestDS {
	GenericCollectionModel<Group> getGroups(
			Map<GroupQueryParameter, String> groupQueryParameters,
			Map<PagingAndSortingParameter, String> pagingAndSortingParameters)
			throws Exception;

	Group getGroupById(String groupId) throws Exception;

	Group updateGroup(String groupId, Group group) throws Exception;

	/**
	 * to create new group, url is generated by engin
	 * 
	 * @param group
	 * @return
	 * @throws Exception
	 */
	Group createGroup(Group group) throws Exception;

	void deleteGroup(String groupId) throws Exception;

	MemberShip createMemberToGroup(String groupId, String userId)
			throws Exception;

	void deleteMemberFromGroup(String groupId, String userId) throws Exception;

}
