package nz.co.activiti.tutorial.ds.group;

import org.activiti.engine.identity.Group;

public interface GroupDS {

	Group getGroupById(String groupId) throws Exception;

	Group updateGroup(String groupId, Group group) throws Exception;

	/**
	 * to create new group, url is generated by engin
	 * 
	 * @param group
	 * @return
	 * @throws Exception
	 */
	Group createGroup(Group group) throws Exception;

	void deleteGroup(String groupId) throws Exception;

	void createMemberToGroup(String groupId, String userId) throws Exception;

	void deleteMemberFromGroup(String groupId, String userId) throws Exception;

}
